services:
  - type: web
    name: cropguard-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    rootDir: cropguard-ai/backend
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: PORT
        value: 5000
      - key: PYTHONPATH
        value: ./cropguard-ai/backend
